language: node_js
sudo: false

node_js:
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - g++-4.9

before_install:
  - npm install -g node-gyp

services:
  - mongodb
  - redis-server

cache:
  directories:
    node_modules

install:
  - pwd && npm install

env:
- CXX=g++-4.9